data:
  path: './data/sa.npz'
  n_samples: 64
  n_steps: 21
  double_precision: true

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 32
