data:
  path: './data/lti.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'lti_dkbf'
  encoder_layers: 1
  decoder_layers: 1
  latent_dimension: 32
  koopman_dimension: 4
  const_term: true
  activation: "none"
  weight_init: "xavier_uniform"
  gain: 0.01

training:
  n_epochs: 1000
  save_interval: 10
  load_checkpoint: false
  learning_rate: 5e-3
  decay_rate: 0.999
  reconstruction_weight: 1.0
  dynamics_weight: 1.0
  chop_mode: "unfold"
  chop_step: 0.5
  sweep_lengths: [3, 5, 7]
  sweep_epoch_step: 200