data:
  path: './data/ex2.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'lti_ldm'
  type: "NN"   # Options: "NN", "LSTM", "GNN"
  encoder_layers: 0
  processor_layers: 1
  decoder_layers: 0
  latent_dimension: 32
  activation: "none"
  weight_init: "xavier_uniform"
  input_order: "cubic"

training:
  n_epochs: 200
  save_interval: 10
  load_checkpoint: True
  learning_rate: 1e-2
  decay_rate: 0.999
  reconstruction_weight: 0.0
  dynamics_weight: 1.0 
  # NODE-specific parameters
  sweep_lengths: [100, 150, 200, 300, 501]
  Tolerance_sweeps: #[1e-3,1e-4,1e-5, 1e-6,1e-7,1e-8, 1e-9,1e-10, 1e-11, 1e-12]
  sweep_epoch_step: 20
  ode_method: 'dopri5'
  rtol: 1e-7
  atol: 1e-9