data:
  path: './data/ltd.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  - type: "scaler"
    mode: "std"
  - type: "delay"
    delay: 1

transform_u:
  type: "delay"
  delay: 1

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'ltd_ldm_wf'
  encoder_layers: 0
  processor_layers: 1
  decoder_layers: 0
  latent_dimension: 32
  activation: "none"
  weight_init: "xavier_uniform"
  input_order: "cubic"

training:
  n_epochs: 500
  save_interval: 10
  load_checkpoint: false
  learning_rate: 5e-3
  decay_rate: 0.999
  reconstruction_weight: 1.0
  dynamics_weight: 1.0
  weak_form_params:
    N: 13
    dN: 2
    ordpol: 2
    ordint: 2
